# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee0caff3daf70ca877e6f3ddc870e0ff60b3f7d55ef23595f72b83f613462d4ba103a44b83344d87f7dfcffa6cd98e2c0e16a80d493151fab7397876c8c5d767

test:
  secret_key_base: 6c911ba3eddf5389e546b27eba0b87ea29ff4c52fdc9f4df5ba2271bca93c162a214b2951b1a84e4a7169e067750c26af0f00e3f44b3082a5680ce307d0b6920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
